docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v 'c:/Users/TimmyTruong/OneDrive - IRPSX Pty Limited/Documents/DE_Zoomcamp/week_1/ny_taxi/ny_taxi_postgres_data:/var/lib/postgresql/data' \
  -p 5432:5432 \
  postgres:13